### ISSUE TITLE
use new `ipfs get`

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#16]
https://github.com/ipfs/python-ipfs-api/issues/28#issuecomment-146426053
instead of
https://github.com/NexusDevelopment/dapple/blob/master/dapple_core/install.py#L25

**Comment by ryepdx** [comment]
Not quite there yet. Will comment again when this one's handled.

**Comment by ryepdx** [comment]
Done.

**Comment by ryepdx** [comment]
Can this issue be closed now?
