### ISSUE TITLE
`dapple init` requires sudo

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#18]
`dapple init` requires sudo, and then it sets the dappfile to be read-only (requiring sudo to edit).

Neither should be necessary

**Comment by ryepdx** [comment]
I just tested this and didn't need `sudo`. Is this your first time running `dapple init`? The only directory it should be writing to is the current working directory, and I don't imagine you were in one that would have required `sudo` for that. It will also write a default `.dapplerc` file to your home directory if it's your first time running it. It shouldn't need `sudo` to write to your home directory, but it's possible that your environment is somehow making Python confused about where your home directory is.

**Comment by nmushegian** [comment]
cannot reproduce. weird!
