### ISSUE TITLE
add `dapple new test` command

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#22]
`dapple new test ExampleContract`

should generate:

`example_contract.sol`:

```
contract ExampleContract {
}
```
`example_contract_test.sol`:
```
contract ExampleContractTest is Test {
    ExampleContract target;
    function setUp() {
        target = new ExampleContract(  );
    }
    function test___ () {
        
    }
}

**Comment by drupalnomad** [comment]
https://github.com/NexusDevelopment/dapple/pull/76

**Comment by nmushegian** [comment]
* `new` will be an entire collection of commands, the docopt can handle `dapple new test <testname>`
* This should probably make use of the `constants` directory

**Comment by drupalnomad** [comment]
The problem is that if you have `dapple new test <testname>` this triggers the `dapple test` command. If we have a separate `dapple new <thing>` you can't define thing-specific parameters in docopt.txt

I'll work on putting the Solidity code into a lodash template in the constants directory.

**Comment by nmushegian** [comment]
In the first example of the doc they are able to do `naval_fate ship shoot <x> <y>`

http://docopt.org/

**Comment by mhhf** [comment]
while it's true, that docopt can't recognize several command at once, it dosen't mean you can't handle this case at all. E.g. you could catch this in main.js:
```
} else if( cli.new && cli.test ) {
   // init test contract
} else if( cli.test ) {
   // test something
} else ...
```

**Comment by drupalnomad** [comment]
Okay I updated https://github.com/NexusDevelopment/dapple/pull/76
