### ISSUE TITLE
the naming things issue

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#23]
`.dapple`: It is a bit annoying that this is invisible. The `dappfile` or at least the packages subtree should be in a visible file

`core` could be called something which implies that it's not used in deployed contracts and it's specific to dapple

**Comment by ryepdx** [comment]
Maybe instead of `.dapple/dappfile` and `.dapple/packages` we have `dapplefile` and `dapple_packages`? Or maybe it be better to rename `.dapple` to just `dapple`. Thoughts?

**Comment by ryepdx** [comment]
Going with `.dapple`=>`dapple` per our Slack convo.

**Comment by ryepdx** [comment]
`core` => `dapple_dev`?

**Comment by ryepdx** [comment]
This should be closed now.
