### ISSUE TITLE
No handlers could be found for logger "eth.pow"

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#28]
this appears every time you do anything. might need a PR to pyethereum

**Comment by ryepdx** [comment]
Yeah, I've dug into this one. It definitely comes from PyEthereum.

**Comment by ryepdx** [comment]
If we do a JS rewrite per #21, this will no longer be an issue.

**Comment by juanfranblanco** [comment]
It has been driving me nuts that since I started, I will vote and help on the port to js. It will also allow for easier integration to developer tools

**Comment by juanfranblanco** [comment]
I have just seen you have started awesome

**Comment by nmushegian** [comment]
no longer relevant
