### ISSUE TITLE
filter dapple classes out of build output

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#41]
classes that inherit from Test or Debug should be filtered out of the build pipeline after the test step and before big bundles are emitted

**Comment by nmushegian** [comment]
looks like this is happening at some point before js_module but after classes.json

**Comment by ryepdx** [comment]
Kind of. The Test, Tester, and Debug contracts are being filtered out, but the classes which inherit from them are not.

**Comment by ryepdx** [comment]
I think this one and #77 can be addressed with the same code. I'm on it. Barring finding any more bugs in the process of handling this one, I think I'll call v0.2 ready to go once these two are done.
