### ISSUE TITLE
use native solc if available to speed things up.

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#44]
this requires making a solc wrapper that takes the same convenient input format as npm solc

**Comment by ryepdx** [comment]
Addressed by PR #47

**Comment by nmushegian** [comment]
> Granted, it's not the cleanest implementation

You want to keep the issue open for this reason?

**Comment by ryepdx** [comment]
Yeah, I'll have it cleaned up pretty quickly here. Will comment here again when it's cleaner.

**Comment by ryepdx** [comment]
Cleaned up now!
