### ISSUE TITLE
very slow startup time

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#49]
Starting `dapple` with no args just to get the usage takes over 1 second. This is longer than it takes solc to compile the package

**Comment by ryepdx** [comment]
Looks like most of the time is being spent in `require`s. NodeJS seems to load required files eagerly, so it was basically importing *everything* that might ever be needed in executing any of Dapple's functions before showing the usage message. Moving the `docopt`-related `require`s to the top of `main.js` reduced the startup time for Dapple without arguments from 7-9 seconds to around 400 milliseconds.

**Comment by ryepdx** [comment]
Lazy loading some of the lesser-used modules, and especially making everything `streams.js` exports lazy-loaded, reduced running time for `dapple build` in dappsys from 10 seconds down to 6 seconds.

Closing this one out, since the original issue has been addressed.
