### ISSUE TITLE
filter `dapple test` by regex

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#70]

**Comment by mhhf** [comment]
I suppose you mean the filtering of functions e.g. `dapple test -e "^testFooIn.*"`?

**Comment by nmushegian** [comment]
I was thinking filter by test contract names, but it could be both or specified by option

**Comment by nmushegian** [comment]
case-insensitive and otherwise "loose" matches included, e.g. `dapple test -r token` would test EthTokenTest, BaseTokenTest, etc

**Comment by ryepdx** [comment]
Appears to have been handled by #78.
