### ISSUE TITLE
subpackage ignore lists are not respected

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#71]
to reproduce:

1) create a package and ignore a file which doesn't compile. The package will build.
2) add it as a subpackage and try to build. It tries to compile the ignored file in the subpackage.

**Comment by ryepdx** [comment]
Yeah, that's an artifact of a previous assumption colliding with present
reality. I'd initially planned that files ignored in the dappfile would get
pulled out during the publishing process. But that doesn't really make
sense if we're going with a Github-centric approach now.

On Mon, Jan 11, 2016 at 4:52 PM, Nikolai Mushegian <notifications@github.com

**Comment by ryepdx** [comment]
Closing this, as it seems to have been resolved on my end. Please re-open if that's not the case for you.
